[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_unused_ignores = True
no_error_summary = True

[mypy-app.application]
ignore_errors = True
[mypy-app.db.queries]
ignore_errors = True
[mypy-app.modules.llm_chat.*]
ignore_errors = True
[mypy-app.modules.maps.service]
ignore_errors = True
[mypy-app.modules.population_surveillance.service]
ignore_errors = True
[mypy-app.modules.hematology.extractor]
ignore_errors = True
[mypy-app.modules.hematology.formatter]
ignore_errors = True
[mypy-app.modules.ml.metadata]
ignore_errors = True
