from __future__ import annotations

from .schemas import ResidenceZoneOut

_ZONES: tuple[ResidenceZoneOut, ...] = (
    ResidenceZoneOut(
        code="do-sd-dn",
        label="Distrito Nacional",
        province="Distrito Nacional",
        municipality="Santo Domingo de Guzman",
        lat=18.4861,
        lng=-69.9312,
    ),
    ResidenceZoneOut(
        code="do-sd-este",
        label="Santo Domingo Este",
        province="Santo Domingo",
        municipality="Santo Domingo Este",
        lat=18.4800,
        lng=-69.8600,
    ),
    ResidenceZoneOut(
        code="do-sd-norte",
        label="Santo Domingo Norte",
        province="Santo Domingo",
        municipality="Santo Domingo Norte",
        lat=18.5500,
        lng=-69.9500,
    ),
    ResidenceZoneOut(
        code="do-sd-oeste",
        label="Santo Domingo Oeste",
        province="Santo Domingo",
        municipality="Santo Domingo Oeste",
        lat=18.5000,
        lng=-70.0300,
    ),
    ResidenceZoneOut(
        code="do-sd-alcarrizos",
        label="Los Alcarrizos",
        province="Santo Domingo",
        municipality="Los Alcarrizos",
        lat=18.5142,
        lng=-70.0517,
    ),
    ResidenceZoneOut(
        code="do-stgo-santiago",
        label="Santiago",
        province="Santiago",
        municipality="Santiago de los Caballeros",
        lat=19.4517,
        lng=-70.6970,
    ),
    ResidenceZoneOut(
        code="do-stgo-janico",
        label="Janico",
        province="Santiago",
        municipality="Janico",
        lat=19.2333,
        lng=-70.8000,
    ),
    ResidenceZoneOut(
        code="do-stgo-sajoma",
        label="San Jose de las Matas",
        province="Santiago",
        municipality="San Jose de las Matas",
        lat=19.3333,
        lng=-70.9333,
    ),
    ResidenceZoneOut(
        code="do-vega-la-vega",
        label="La Vega",
        province="La Vega",
        municipality="La Vega",
        lat=19.2196,
        lng=-70.5300,
    ),
    ResidenceZoneOut(
        code="do-vega-jarabacoa",
        label="Jarabacoa",
        province="La Vega",
        municipality="Jarabacoa",
        lat=19.1208,
        lng=-70.6375,
    ),
    ResidenceZoneOut(
        code="do-vega-constanza",
        label="Constanza",
        province="La Vega",
        municipality="Constanza",
        lat=18.9067,
        lng=-70.7383,
    ),
    ResidenceZoneOut(
        code="do-espm-moca",
        label="Moca",
        province="Espaillat",
        municipality="Moca",
        lat=19.3922,
        lng=-70.5233,
    ),
    ResidenceZoneOut(
        code="do-pp-puerto-plata",
        label="Puerto Plata",
        province="Puerto Plata",
        municipality="Puerto Plata",
        lat=19.7930,
        lng=-70.6911,
    ),
    ResidenceZoneOut(
        code="do-pp-sosua",
        label="Sosua",
        province="Puerto Plata",
        municipality="Sosua",
        lat=19.7614,
        lng=-70.5139,
    ),
    ResidenceZoneOut(
        code="do-duarte-sfm",
        label="San Francisco de Macoris",
        province="Duarte",
        municipality="San Francisco de Macoris",
        lat=19.3003,
        lng=-70.2527,
    ),
    ResidenceZoneOut(
        code="do-mts-nagua",
        label="Nagua",
        province="Maria Trinidad Sanchez",
        municipality="Nagua",
        lat=19.3769,
        lng=-69.8477,
    ),
    ResidenceZoneOut(
        code="do-samana-samana",
        label="Samana",
        province="Samana",
        municipality="Samana",
        lat=19.2097,
        lng=-69.3356,
    ),
    ResidenceZoneOut(
        code="do-samana-terrenas",
        label="Las Terrenas",
        province="Samana",
        municipality="Las Terrenas",
        lat=19.3061,
        lng=-69.5328,
    ),
    ResidenceZoneOut(
        code="do-mts-cotui",
        label="Cotui",
        province="Sanchez Ramirez",
        municipality="Cotui",
        lat=19.0567,
        lng=-70.1511,
    ),
    ResidenceZoneOut(
        code="do-mons-bonao",
        label="Bonao",
        province="Monsenor Nouel",
        municipality="Bonao",
        lat=18.9397,
        lng=-70.4081,
    ),
    ResidenceZoneOut(
        code="do-spm-spm",
        label="San Pedro de Macoris",
        province="San Pedro de Macoris",
        municipality="San Pedro de Macoris",
        lat=18.4534,
        lng=-69.3047,
    ),
    ResidenceZoneOut(
        code="do-lr-la-romana",
        label="La Romana",
        province="La Romana",
        municipality="La Romana",
        lat=18.4273,
        lng=-68.9728,
    ),
    ResidenceZoneOut(
        code="do-la-higuey",
        label="Higuey",
        province="La Altagracia",
        municipality="Higuey",
        lat=18.6153,
        lng=-68.7078,
    ),
    ResidenceZoneOut(
        code="do-la-punta-cana",
        label="Punta Cana",
        province="La Altagracia",
        municipality="Punta Cana",
        lat=18.5821,
        lng=-68.4059,
    ),
    ResidenceZoneOut(
        code="do-sc-san-cristobal",
        label="San Cristobal",
        province="San Cristobal",
        municipality="San Cristobal",
        lat=18.4158,
        lng=-70.1083,
    ),
    ResidenceZoneOut(
        code="do-peravia-bani",
        label="Bani",
        province="Peravia",
        municipality="Bani",
        lat=18.2789,
        lng=-70.3322,
    ),
    ResidenceZoneOut(
        code="do-azua-azua",
        label="Azua",
        province="Azua",
        municipality="Azua",
        lat=18.4525,
        lng=-70.7347,
    ),
    ResidenceZoneOut(
        code="do-sj-sjm",
        label="San Juan de la Maguana",
        province="San Juan",
        municipality="San Juan de la Maguana",
        lat=18.8061,
        lng=-71.2289,
    ),
    ResidenceZoneOut(
        code="do-barahona-barahona",
        label="Barahona",
        province="Barahona",
        municipality="Barahona",
        lat=18.2094,
        lng=-71.1022,
    ),
    ResidenceZoneOut(
        code="do-valverde-mao",
        label="Mao",
        province="Valverde",
        municipality="Mao",
        lat=19.5555,
        lng=-71.0775,
    ),
)


def list_residence_zones() -> list[ResidenceZoneOut]:
    return sorted(_ZONES, key=lambda zone: (zone.province, zone.label))


def get_residence_zone(code: str | None) -> ResidenceZoneOut | None:
    if not code:
        return None
    normalized = code.strip().lower()
    return next((zone for zone in _ZONES if zone.code == normalized), None)
